### ISSUE TITLE
Code Release

### ISSUE THREAD

**Issue by Lzyin** [PJLab-ADG/OpenPCSeg#15]
Thanks for your interesting work!  When will the code (UniSeg) be released?

**Comment by TobyZhouWei** [comment]
Hi, like you, I am looking forward to the publication of UniSeg!!

**Comment by the-king-of-yhq** [comment]
Hi, like you, I am looking forward to the publication of UniSeg!!

**Comment by BurtonMan** [comment]
Thanks for your interesting work! 
UniSeg has been published. When will the UniSeg)be released?

**Comment by UQHTy** [comment]
Reading comments...
